path:
  ckpt_path: ""
  log_path: ""
  result_path: ""
checkpoint:
  pretrained: "/home/s2220411/Code/Log_data/pretrained/900000.pth.tar"
  path_hifigan: "/home/ldap-users/s2220411/Code/FastSpeech2_multilingual"
optimizer:
  batch_size: 40
  batch_size_eval: 1
  num_sample: 50
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [200000, 300000, 400000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 1000
  synth_step: 1000
  val_step: 1000
  save_step: 10000
loss:
  noise_loss: "l1"
  dur_loss: "mse"
  pitch_loss: "l1"
  cwt_loss: "l1"
  # cwt_add_f0_loss: false
  lambda_f0: 1.0
  lambda_uv: 1.0
  lambda_ph_dur: 1.0
  lambda_word_dur: 1.0
  lambda_sent_dur: 1.0